import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Providers } from "./redux/provider";
import { ApolloWrapper } from "@/lib/apollo-wrapper";
import { SessionProvider } from "next-auth/react";
import { NextAuthProvider } from "./providers";
import Navbar from "../components/navbar/Navbar";
import Footer from "../components/footer/Footer";
import SignIn from "./auth/signin/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface Iprops {
  session: any;
  children: React.ReactNode;
}

export default function RootLayout({ children, session }: Iprops) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <NextAuthProvider session={session}>
            <ApolloWrapper>
              <div className="">
                {/* <SignIn /> */}
                <Navbar />
                {children}
                <Footer />
              </div>
            </ApolloWrapper>
          </NextAuthProvider>
        </Providers>
      </body>
    </html>
  );
}
