import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Providers } from "./redux/provider";
import { ApolloWrapper } from "@/lib/apollo-wrapper";
import { NextAuthProvider } from "./providers";
import Navbar2 from "@/components/navbar/Navbar2";
import Footer from "../components/footer/Footer";

import { Session } from "next-auth";
import { headers } from "next/headers";

import Drawer from "react-modern-drawer";
import { RxHamburgerMenu } from "react-icons/rx";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface Iprops {
  session: any;
  children: React.ReactNode;
}

async function getSession(cookie: string): Promise<Session> {
  const response = await fetch(`${process.env.NEXTAUTH_URL}/api/auth/session`, {
    headers: {
      cookie,
    },
  });

  const session = await response.json();
  console.log("session", session);
  return Object.keys(session).length > 0 ? session : null;
}

export default async function RootLayout({ children }: Iprops) {
  const session = await getSession(headers().get("cookie") ?? "");

  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <NextAuthProvider session={session}>
            <ApolloWrapper>
              <div className="font-sans">
                {/* <Navbar2 /> */}
                <div className="min-h-[80vh]">{children}</div>

                <Footer />
              </div>
            </ApolloWrapper>
          </NextAuthProvider>
        </Providers>
      </body>
    </html>
  );
}
